{{- $tenantId := include "logclaw.tenantId" . -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "logclaw-platform.fullname" . }}-registry-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logclaw-platform.labels" . | nindent 4 }}
  annotations:
    logclaw.io/tenant-id: {{ $tenantId | quote }}
    logclaw.io/secret-purpose: "image-pull"
spec:
  refreshInterval: {{ .Values.global.secretStore.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ include "logclaw-platform.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: logclaw-registry-pull-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {{ `{{ .dockerconfigjson | b64dec }}` }}
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: {{ printf "logclaw/%s/global/registry-pull-secret" $tenantId | quote }}
        property: dockerconfigjson
