apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "logclaw-flink.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logclaw-flink.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "logclaw-flink.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "logclaw-flink.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
